SELECT wls."DATE"
    ,"WILLREITIND"
    ,"CREACBW027SBOG"
    ,"RHEACBW027SBOG"
    ,"CORESTICKM159SFRBATL"
    ,"UNRATE"
FROM re_wilshire as wls
JOIN cpi_less_fe_daily AS cpd ON cpd."DATE" = wls."DATE"
JOIN re_comm_daily AS rcd ON rcd."DATE" = wls."DATE"
JOIN re_resd_daily AS rrd ON rrd."DATE" = wls."DATE"
JOIN un_rate_daily AS urd ON urd."DATE" = wls."DATE"